spring.application.name=KafkaDemo
server.port =8081

logging.level.org.apache.kafka=INFO
logging.level.org.springframework.kafka=INFO

# ==============================================
spring.kafka.topic.name=newTopic
spring.kafka.json-topic.name=jsonTopic


# ==============================================
#Step 1: configure properties related to producer

# Address of the kafka broker that the producer sends messages to. (Producer send messages to kafka broker(9090)).
spring.kafka.producer.bootstrap.servers=localhost:9092

# serializer used to convert "message key" from "java object" to byte[] (byte array) before sending to kafka broker.
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

# serializer used to convert "message value" from "java object" to byte[] (byte array) before sending to kafka broker.
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


# ==============================================
#Step 2: configure properties related to consumer

# Address of the kafka broker that the consumer needs to connect to (Format: host:port) :
# (Consumer needs to connect with kafka-broker port(9092) to consume messages)
spring.kafka.consumer.bootstrap.servers=localhost:9092

# Unique name of the consumer group
# Consumers with same Group id share the messages from a topic.
spring.kafka.consumer.group-id=myconsumergroup

# Determines from where the consumer starts reading messages, when no commited offset exists(or) provided from the consumer group.
# If value = earliest, It will read messages from the beginning
# if value = latest, It will read only newly arriving messages only
spring.kafka.consumer.auto-offset-reset=earliest

# Deserializer used to convert the message key from "(byte array)byte[] to "Java object"
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Deserializer used to convert the message value from "(byte array)byte[] to "Java object".
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Package containing your event classes (It means the kafka consumer can deserialize all the classes
# from that package and we can add specific classes also)
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# For values, we use "JsonSerializer" and "JsonDeserializer".



